//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransportHub.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LibraryNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibraryNames() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TransportHub.Core.Resources.LibraryNames", typeof(LibraryNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .NET.
        /// </summary>
        internal static string _NET {
            get {
                return ResourceManager.GetString(".NET", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Autofac.
        /// </summary>
        internal static string Autofac {
            get {
                return ResourceManager.GetString("Autofac", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Avalonia UI.
        /// </summary>
        internal static string Avalonia_UI {
            get {
                return ResourceManager.GetString("Avalonia UI", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu CommunityToolkit.Mvvm.
        /// </summary>
        internal static string CommunityToolkit_Mvvm {
            get {
                return ResourceManager.GetString("CommunityToolkit.Mvvm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu FluentAvalonia.
        /// </summary>
        internal static string FluentAvalonia {
            get {
                return ResourceManager.GetString("FluentAvalonia", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu FluentAvalonia.ProgressRing.
        /// </summary>
        internal static string FluentAvalonia_ProgressRing {
            get {
                return ResourceManager.GetString("FluentAvalonia.ProgressRing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lindronics.OneOf.Result.
        /// </summary>
        internal static string Lindronics_OneOf_Result {
            get {
                return ResourceManager.GetString("Lindronics.OneOf.Result", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lorem.Universal.Net.
        /// </summary>
        internal static string Lorem_Universal_Net {
            get {
                return ResourceManager.GetString("Lorem.Universal.Net", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu MessageBox.Avalonia.
        /// </summary>
        internal static string MessageBox_Avalonia {
            get {
                return ResourceManager.GetString("MessageBox.Avalonia", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Microsoft.JSInterop.
        /// </summary>
        internal static string Microsoft_JSInterop {
            get {
                return ResourceManager.GetString("Microsoft.JSInterop", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OneOf.
        /// </summary>
        internal static string OneOf {
            get {
                return ResourceManager.GetString("OneOf", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Open Sans.
        /// </summary>
        internal static string Open_Sans {
            get {
                return ResourceManager.GetString("Open Sans", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Riok.Mapperly.
        /// </summary>
        internal static string Riok_Mapperly {
            get {
                return ResourceManager.GetString("Riok.Mapperly", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.
        /// </summary>
        internal static string Serilog {
            get {
                return ResourceManager.GetString("Serilog", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Enrichers.AssemblyName.
        /// </summary>
        internal static string Serilog_Enrichers_AssemblyName {
            get {
                return ResourceManager.GetString("Serilog.Enrichers.AssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Enrichers.Context.
        /// </summary>
        internal static string Serilog_Enrichers_Context {
            get {
                return ResourceManager.GetString("Serilog.Enrichers.Context", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Enrichers.Demystifier.
        /// </summary>
        internal static string Serilog_Enrichers_Demystifier {
            get {
                return ResourceManager.GetString("Serilog.Enrichers.Demystifier", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Enrichers.Environment.
        /// </summary>
        internal static string Serilog_Enrichers_Environment {
            get {
                return ResourceManager.GetString("Serilog.Enrichers.Environment", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Enrichers.Memory.
        /// </summary>
        internal static string Serilog_Enrichers_Memory {
            get {
                return ResourceManager.GetString("Serilog.Enrichers.Memory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Enrichers.Process.
        /// </summary>
        internal static string Serilog_Enrichers_Process {
            get {
                return ResourceManager.GetString("Serilog.Enrichers.Process", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Enrichers.Sensitive.
        /// </summary>
        internal static string Serilog_Enrichers_Sensitive {
            get {
                return ResourceManager.GetString("Serilog.Enrichers.Sensitive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Enrichers.Thread.
        /// </summary>
        internal static string Serilog_Enrichers_Thread {
            get {
                return ResourceManager.GetString("Serilog.Enrichers.Thread", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Exceptions.
        /// </summary>
        internal static string Serilog_Exceptions {
            get {
                return ResourceManager.GetString("Serilog.Exceptions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Sinks.Console.
        /// </summary>
        internal static string Serilog_Sinks_Console {
            get {
                return ResourceManager.GetString("Serilog.Sinks.Console", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Sinks.Debug.
        /// </summary>
        internal static string Serilog_Sinks_Debug {
            get {
                return ResourceManager.GetString("Serilog.Sinks.Debug", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Sinks.Discord.
        /// </summary>
        internal static string Serilog_Sinks_Discord {
            get {
                return ResourceManager.GetString("Serilog.Sinks.Discord", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Sinks.File.
        /// </summary>
        internal static string Serilog_Sinks_File {
            get {
                return ResourceManager.GetString("Serilog.Sinks.File", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serilog.Sinks.PeriodicBatching.
        /// </summary>
        internal static string Serilog_Sinks_PeriodicBatching {
            get {
                return ResourceManager.GetString("Serilog.Sinks.PeriodicBatching", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tabler Icons.
        /// </summary>
        internal static string Tabler_Icons {
            get {
                return ResourceManager.GetString("Tabler Icons", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Xamarin.AndroidX.
        /// </summary>
        internal static string Xamarin_AndroidX {
            get {
                return ResourceManager.GetString("Xamarin.AndroidX", resourceCulture);
            }
        }
    }
}
